
site_name: Cristian Sulea
site_url: https://cristian.sulea.net/
site_description: Personal website and knowledge base.
site_author: Cristian Sulea

theme:
  name: mkdocs
  custom_dir: custom_theme/

